image: python:latest

before_script:
  - python3 -V  
  - pip3 install boto3

stages:
  - build
  - test

first:
  stage: build
  tags:
    - docker
  script:
    - python3 s3d.py anewdawnbucket test.txt imtestingyou.txt
    - touch new.txt
    - echo 'ddddd' > new.txt
    - cat imtestingyou.txt
  artifacts:
    paths:
    - test.txt
    - new.txt

second:
  stage: test
  tags:
    - ebash
  script:
    - ls -la
    - python3 s3d.py anewdawnbucket test.txt test.txt
    - cat test.txt
  
#  artifacts:
#    paths:
#    - test.txt

